# Generated by Django 6.0.5 on 2026-05-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_high_fiber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_low_carb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_low_sugar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
