# Generated by Django 6.0.5 on 2026-05-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_is_high_fiber_meal_is_low_carb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='recommended_for',
            field=models.CharField(choices=[('type1', 'Diabète Type 1'), ('type2', 'Diabète Type 2'), ('prediabetes', 'Prédiabète')], default='type2', max_length=20),
        ),
        migrations.AddField(
            model_name='meal',
            name='sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
